services:
  web:
    build: ./trade_reads_backend # will build from this folder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./trade_reads_backend/:/usr/src/djangotrade_reads_backend #
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=tradereadsdb

volumes:
  postgres_data:
